window.BOOKDATA || (window.BOOKDATA = {});

/* Extra, deeper notes added for each topic */
window.BOOKDATA.extra = {
	"1_1": "<p><b>Key point:</b> {L} grew out of a specific problem and its design reflects that goal. Always relate new syntax back to the history - it explains why the language behaves the way it does and where it fits in the wider programming landscape.</p>",
	"1_2": "<p><b>Key point:</b> No language is best at everything. {L} wins in its niche - pick it for that strength, not because it is popular. Knowing its advantages and limits helps you decide between {L}, C++, JavaScript, and other tools.</p>",
	"1_3": "<p><b>Key point:</b> A correct install is half the battle. After installing, run the version command and a tiny test program to prove the toolchain works before moving on to real code.</p>",
	"1_4": "<p><b>Key point:</b> The first program is a health check of your whole setup: editor, compiler or interpreter, and runtime. If it prints, the pipeline works and everything else builds on top of it.</p>",
	"1_5": "<p><b>Key point:</b> Your editor is your daily workspace. Spend a little time on shortcuts, themes, and the built-in terminal - small setup investments pay off in speed for every later project.</p>",
	"1_6": "<p><b>Key point:</b> Learn the difference between compile time (checks types before running) and run time (when the code actually executes). Debuggers narrow errors down to the exact line and variable state.</p>",
	"1_7": "<p><b>Key point:</b> Comments should say <i>why</i>, not <i>what</i>. Good names already explain what the code does; comments capture the reasoning that is not obvious from the code itself.</p>",
	"1_8": "<p><b>Key point:</b> A tidy project layout makes code predictable. Follow the community convention for {L} - it lets anyone open the folder and immediately know where the source, tests, and config live.</p>",
	"2_1": "<p><b>Key point:</b> Prefer constants over magic numbers and give variables descriptive names. The single best habit for avoiding bugs is making intent visible in the names you choose.</p>",
	"2_2": "<p><b>Key point:</b> Types are a contract. In strongly typed languages the compiler catches whole classes of mistakes early; understanding types means understanding memory and behavior.</p>",
	"2_3": "<p><b>Key point:</b> Operators have precedence and can be combined. Write parentheses when a compound expression's order is not obvious - clarity beats cleverness.</p>",
	"2_4": "<p><b>Key point:</b> Strings are everywhere and full of hidden details: encoding, immutability, and escaping. Master the common methods (upper, lower, split, replace, length) - they do 90% of text work.</p>",
	"2_5": "<p><b>Key point:</b> Numbers come with precision limits and conversion rules. Know when to use integers, floats, and string conversion, and be wary of floating-point rounding in money or exact comparisons.</p>",
	"2_6": "<p><b>Key point:</b> Conditionals branch your logic. Order matters - put the most specific or most likely case first, and always consider what happens when no branch matches.</p>",
	"2_7": "<p><b>Key point:</b> Loops repeat work and are a top source of errors (off-by-one, infinite loops). Ask three questions: how many times, what changes each pass, and how the loop stops.</p>",
	"2_8": "<p><b>Key point:</b> Switch/match is a cleaner way to pick one of many cases than a long if/else chain. It maps one value to a clear set of outcomes and often runs faster.</p>",
	"3_1": "<p><b>Key point:</b> Functions turn repeated logic into a single named unit. Good functions do one thing, have clear inputs and outputs, and are short enough to read in one glance.</p>",
	"3_2": "<p><b>Key point:</b> Parameters are the function's inputs; return values are its outputs. Defaults and named arguments make functions flexible while keeping call sites readable.</p>",
	"3_3": "<p><b>Key point:</b> Scope is where a variable lives. Variables declared inside a function are not visible outside it. Respecting scope prevents accidental name collisions and unexpected state changes.</p>",
	"3_4": "<p><b>Key point:</b> Classes bundle data (fields) with behavior (methods). An object is one instance of a class; the constructor runs when you create it. This is the heart of object-oriented programming.</p>",
	"3_5": "<p><b>Key point:</b> Inheritance lets a child class reuse and extend a parent's behavior; polymorphism lets different classes answer the same call in their own way. This is what makes OOP code extensible.</p>",
	"3_6": "<p><b>Key point:</b> Interfaces and abstract types define <i>what</i> an object can do without saying <i>how</i>. They let you write code against a contract, which is the foundation of clean, testable design.</p>",
	"3_7": "<p><b>Key point:</b> Arrays and collections store many values in order. Choose the right container for the job - fixed-size arrays, resizable lists, or sets - based on how you add, read, and search data.</p>",
	"3_8": "<p><b>Key point:</b> Dictionaries/maps store key-value pairs for fast lookup. Whenever you need to find something by a name or id, a map beats scanning a list almost every time.</p>",
	"4_1": "<p><b>Key point:</b> Reading files opens a world of real data. Always handle the file cleanly (close it or use a context manager) and anticipate errors when the file is missing or unreadable.</p>",
	"4_2": "<p><b>Key point:</b> Writing files persists your program's results. Use the correct mode (append vs overwrite), encode text properly, and decide whether to flush/buffer before the process ends.</p>",
	"4_3": "<p><b>Key point:</b> JSON is the lingua franca of data exchange. Learning to serialize (object to text) and deserialize (text to object) unlocks working with APIs, configs, and saved state.</p>",
	"4_4": "<p><b>Key point:</b> Databases store structured data at scale. You connect with a driver, run queries, and manage rows; learning parameterization protects against injection attacks.</p>",
	"4_5": "<p><b>Key point:</b> User input arrives as text and is rarely perfect. Validate, convert, and clean it - assume users will type the wrong thing and make your program survive that.</p>",
	"4_6": "<p><b>Key point:</b> Output and logging reveal what your program does. Logs with timestamps and levels (info, warn, error) are your eyes into a running system; write them thoughtfully.</p>",
	"4_7": "<p><b>Key point:</b> Configuration separates what changes (settings) from what changes rarely (code). Environment variables and config files let the same program run differently in dev, test, and production.</p>",
	"4_8": "<p><b>Key point:</b> Time and dates are trickier than they look: timezones, formats, and leap seconds. Store and compute in UTC, then format for display in the user's local zone.</p>",
	"5_1": "<p><b>Key point:</b> Errors are a normal part of running software, not a failure. Understand the difference between syntax errors (caught before run), runtime errors, and logic errors (wrong results).</p>",
	"5_2": "<p><b>Key point:</b> Try/catch lets you respond to errors gracefully instead of crashing. Catch the specific error you expect, handle it, and let the program continue - but never swallow errors silently.</p>",
	"5_3": "<p><b>Key point:</b> Error logging keeps a record that is invaluable later. Log the error message, the stack trace, and enough context to reproduce the issue in production.</p>",
	"5_4": "<p><b>Key point:</b> Security is not a feature added at the end; it is a design concern. Validate inputs, follow least privilege, and never trust data coming from outside the program.</p>",
	"5_5": "<p><b>Key point:</b> Hashing converts data to a fixed-length fingerprint - it is one-way and ideal for passwords and integrity checks. Encryption is two-way and meant for confidentiality. Do not confuse the two.</p>",
	"5_6": "<p><b>Key point:</b> Input validation rejects bad data before it causes harm. Whitelist allowed values, check types and lengths, and reject anything unexpected rather than trying to guess intent.</p>",
	"5_7": "<p><b>Key point:</b> Authentication proves who you are; authorization decides what you can do. Sessions and tokens keep the user's identity between requests - keep secrets out of code.</p>",
	"5_8": "<p><b>Key point:</b> Secure coding is a mindset: never hard-code secrets, sanitize all inputs, keep dependencies updated, and think about what an attacker could do with each feature you build.</p>",
	"6_1": "<p><b>Key point:</b> System programming is close to the machine - processes, memory, and hardware. It offers great power and speed along with greater responsibility for correctness and safety.</p>",
	"6_2": "<p><b>Key point:</b> A process is an isolated running program; threads share a process's memory. Concurrency speeds things up but needs careful synchronization to avoid races and deadlocks.</p>",
	"6_3": "<p><b>Key point:</b> Memory management decides where data lives and when it is freed. Manual control gives efficiency; managed safety prevents leaks and corruption. Knowing which you are using matters.</p>",
	"6_4": "<p><b>Key point:</b> GPIO pins are the physical mouth and ears of a board: set a pin as input or output, then write or read digital signals to drive LEDs, buttons, and sensors.</p>",
	"6_5": "<p><b>Key point:</b> Interrupts and timers let code react to the real world without busy-waiting. An interrupt fires when an event happens; a timer fires when time has passed. Both keep systems responsive and efficient.</p>",
	"6_6": "<p><b>Key point:</b> Serial protocols (UART, I2C, SPI) connect a board to sensors and peripherals. They trade off speed, wiring, and complexity - choosing the right bus depends on your hardware's needs.</p>",
	"6_7": "<p><b>Key point:</b> Device I/O is the loop of sensing and acting: read a value, condition the signal, react. Most embedded programs are just this loop running at high speed.</p>",
	"6_8": "<p><b>Key point:</b> Querying CPU and OS details lets software adapt: pick the right code path, report diagnostics, or optimize for the host. It makes programs robust across machines.</p>",
	"7_1": "<p><b>Key point:</b> Button events tell you when something was pressed or released. A handler turns that event into a state change or action - the core pattern behind almost every interface.</p>",
	"7_2": "<p><b>Key point:</b> Mechanical switches physically bounce when pressed, generating many false edges. Debouncing ignores those blips by sampling after a short delay, giving one clean press. It is a must for reliable hardware buttons.</p>",
	"7_3": "<p><b>Key point:</b> Mouse events track where the pointer is and which button is down. Click, hover, and drag build the interactive feel of every app - but watch out for coordinate systems and touch fallbacks.</p>",
	"7_4": "<p><b>Key point:</b> A toggle flips between two states. The pattern is simple: keep the current state in data, let the event flip it, then render the UI from that state. Data drives the UI, never the reverse.</p>",
	"7_5": "<p><b>Key point:</b> Sliders let users choose a value from a range. Read the value live to give feedback as it moves, then use the final value when released for cheaper updates.</p>",
	"7_6": "<p><b>Key point:</b> Forms collect and validate user input. Focus events guide users through fields, validation rejects bad input kindly, and submission order matters for a smooth experience.</p>",
	"7_7": "<p><b>Key point:</b> Touch and gestures (tap, swipe, pinch) are the native language of phones. Designing for touch means bigger targets and considering that a finger has no hover state.</p>",
	"7_8": "<p><b>Key point:</b> Good layout adapts: flexible grids, sensible spacing, and responsive rules keep an interface usable from phone to desktop. Design the structure first, decorate later.</p>",
	"8_1": "<p><b>Key point:</b> Keyboard shortcuts are the fastest interface. Mapping a common action to a keypress removes several clicks - a small investment with a big daily payoff for power users.</p>",
	"8_2": "<p><b>Key point:</b> Key events fire as keys go down and up. Inspect which key was pressed and whether it repeats; then decide whether the action should run once or every repeat.</p>",
	"8_3": "<p><b>Key point:</b> Hotkeys combine a modifier with a key (Ctrl+S). Match the combination precisely and consider remapping, since laptop and keyboard layouts differ for everyone.</p>",
	"8_4": "<p><b>Key point:</b> Key codes identify physical keys regardless of what character is typed. They matter for layout-independent shortcuts, games, and input where position beats meaning.</p>",
	"8_5": "<p><b>Key point:</b> Modifiers alter the meaning of a key. Reading Ctrl, Shift, Alt, and Meta state lets you create chord shortcuts - the same key can do many different things.</p>",
	"8_6": "<p><b>Key point:</b> A shortcut table documents every binding, making features discoverable. Consistency with common app shortcuts (Ctrl+S save, Ctrl+C copy) flattens the learning curve.</p>",
	"8_7": "<p><b>Key point:</b> Accessibility keys (Tab, Enter, Escape) let users operate everything without a mouse. A keyboard-complete UI is not a bonus - it is a baseline requirement for inclusive software.</p>",
	"8_8": "<p><b>Key point:</b> Terminal shortcuts are the daily toolkit of command-line work: stopping a process (Ctrl+C), pausing (Ctrl+Z), and navigating history with the arrow keys. Learn them and the terminal feels fast.</p>",
	"9_1": "<p><b>Key point:</b> HTTP is the language of the web: a request (method, URL, headers) gets a response (status code, headers, body). Understanding status codes and methods explains almost every web error you will see.</p>",
	"9_2": "<p><b>Key point:</b> Making an HTTP request means sending a method to a URL and handling the response. Parse JSON, check the status, and catch both network and server errors for a robust client.</p>",
	"9_3": "<p><b>Key point:</b> Clear vocabulary keeps teams aligned. Knowing web page, endpoint, API, hosting, domain, SEO, and responsive design - and how they fit - lets you talk about products precisely.</p>",
	"9_4": "<p><b>Key point:</b> HTML is structure, CSS is style, and {L} is behavior. Keep them separate: hook into elements with IDs and classes, and let {L} add interactivity and data on top.</p>",
	"9_5": "<p><b>Key point:</b> REST treats resources as nouns and HTTP verbs as actions. Predictable URLs, correct status codes, and statelessness make APIs clean, cacheable, and easy to reason about.</p>",
	"9_6": "<p><b>Key point:</b> HTTP is stateless, so sessions and cookies add memory across requests. The server stores what it knows about you and sends a token; the browser echoes it back on each call.</p>",
	"9_7": "<p><b>Key point:</b> WebSockets keep a single open two-way channel between client and server. Unlike request/response, either side can push data anytime - perfect for chat, games, and live feeds.</p>",
	"9_8": "<p><b>Key point:</b> Deployment turns working code into a running service. Build, configure, run, and monitor - and automate it with CI/CD so that shipping a new version is repeatable and safe.</p>",
	"10_1": "<p><b>Key point:</b> Algorithms are step-by-step recipes for computation. Complexity (big O) describes how runtime grows with input size - learn it, because it predicts whether a solution will scale.</p>",
	"10_2": "<p><b>Key point:</b> Recursion solves a problem by breaking it into a smaller version of itself. Every recursive function needs a base case to stop, or it will call forever and overflow the stack.</p>",
	"10_3": "<p><b>Key point:</b> Searching finds a target in data. Linear search scans everything; binary search halves the search space each step but requires sorted input - a classic speed/resource tradeoff.</p>",
	"10_4": "<p><b>Key point:</b> Sorting puts a collection in order. Bubble and selection are simple but slow; quicksort and mergesort are fast and used in practice. Pick by data size and stability needs.</p>",
	"10_5": "<p><b>Key point:</b> Automated tests catch regressions and document expected behavior. A unit test feeds an input and asserts the output; running the suite often keeps the codebase healthy.</p>",
	"10_6": "<p><b>Key point:</b> Debugging is systematic detective work: reproduce, isolate, inspect state, fix, and verify. The most powerful tool is a clear mental model of what the code <i>should</i> do.</p>",
	"10_7": "<p><b>Key point:</b> Best practices - readable names, small functions, good errors, and code review - are what turn working code into maintainable software. They save far more time than they cost.</p>",
	"10_8": "<p><b>Key point:</b> Interviews test fundamentals and communication: data structures, algorithms, and clear reasoning. Practice writing clean code by hand and explaining your trade-offs out loud.</p>"
};
