window.BOOKDATA || (window.BOOKDATA = {});
window.BOOKDATA.snips = window.BOOKDATA.snips || {};

window.BOOKDATA.snips.python = {
	hello: "# Hello World\nprint(\"Hello, World!\")",
	vars: "# Variables & Constants\nname = \"Ali\"\nage = 25\nMAX_USERS = 100   # constant by convention",
	types: "# Data types\ni = 10          # int\nf = 3.14        # float\ns = \"hello\"     # str\nb = True        # bool\nnums = [1,2,3]  # list",
	ops: "# Operators\na, b = 10, 3\nprint(a + b)   # 13\nprint(a // b)  # 3  floor division\nprint(a % b)   # 1  remainder\nprint(a > b)   # True",
	strs: "# Strings & text\ns = \"Hello AlioStore\"\nprint(s.upper())\nprint(s.lower())\nprint(s.replace(\"Hello\", \"Hi\"))\nprint(s.split(\" \"))",
	nums: "# Numbers & conversion\nx = \"42\"\nn = int(x)          # str -> int\nf = float(\"3.5\")    # str -> float\ns = str(100)        # int -> str\nprint(n + 1, f, s)",
	if: "# Conditionals\nage = 18\nif age >= 18:\n    print(\"Adult\")\nelif age >= 13:\n    print(\"Teen\")\nelse:\n    print(\"Child\")",
	loop: "# Loops\nfor i in range(5):\n    print(i)\nn = 0\nwhile n < 3:\n    print(\"tick\", n)\n    n += 1",
	switch: "# Switch via match (Python 3.10+)\ndef desc(code):\n    match code:\n        case 200: return \"OK\"\n        case 404: return \"Not Found\"\n        case _:   return \"Unknown\"\nprint(desc(404))",
	func: "# Functions\ndef greet(name, greeting=\"Hello\"):\n    return f\"{greeting}, {name}!\"\nprint(greet(\"Ali\"))\nprint(greet(\"Ali\", \"Salaam\"))",
	class: "# Classes & objects\nclass Book:\n    def __init__(self, title, pages):\n        self.title = title\n        self.pages = pages\n    def info(self):\n        return f\"{self.title} ({self.pages} pages)\"\nb = Book(\"AlioStore Notes\", 80)\nprint(b.info())",
	arr: "# Arrays / lists\nfruits = [\"apple\", \"banana\", \"cherry\"]\nfruits.append(\"date\")\nfruits.remove(\"banana\")\nprint(fruits)\nprint(fruits[0])\nfor f in fruits:\n    print(f)",
	map: "# Dicts / maps\nuser = {\"name\": \"Ali\", \"age\": 25}\nprint(user[\"name\"])\nuser[\"email\"] = \"ali@example.com\"\nfor k, v in user.items():\n    print(k, \"=\", v)",
	file: "# Reading & writing files\n# write\nwith open(\"note.txt\", \"w\") as f:\n    f.write(\"Hello file!\\n\")\n# read\nwith open(\"note.txt\", \"r\") as f:\n    print(f.read())",
	json: "# JSON\nimport json\ndata = {\"name\": \"Ali\", \"languages\": [\"Python\", \"JS\"]}\ntext = json.dumps(data)          # to string\nloaded = json.loads(text)        # to object\nprint(loaded[\"name\"], loaded[\"languages\"][0])",
	input: "# User input\nname = input(\"What is your name? \")\nage = int(input(\"How old are you? \"))\nprint(f\"Hello {name}, you are {age} years old.\")",
	env: "# Environment & config\nimport os\nport = int(os.getenv(\"PORT\", \"8080\"))\nprint(\"Port:\", port)\nif \"ALISTORE_HOME\" in os.environ:\n    print(\"Home:\", os.environ[\"ALISTORE_HOME\"])",
	time: "# Date & time\nimport datetime\nnow = datetime.datetime.now()\nprint(now)\nprint(now.strftime(\"%Y-%m-%d %H:%M:%S\"))",
	try: "# Try / except\ntry:\n    n = int(\"not-a-number\")\nexcept ValueError as e:\n    print(\"Error:\", e)\nfinally:\n    print(\"Done\")",
	hash: "# Hashing & security\nimport hashlib\ndef hash_password(pw):\n    return hashlib.sha256(pw.encode()).hexdigest()\nprint(hash_password(\"secret123\"))",
	sys: "# System programming\nimport os, platform, sys\nprint(\"OS:\", platform.system())\nprint(\"Machine:\", platform.machine())\nprint(\"Args:\", sys.argv)\nprint(\"CWD:\", os.getcwd())",
	gpio: "# Board configurations (GPIO)\nimport RPi.GPIO as G\nG.setmode(G.BCM)\nG.setup(18, G.OUT)   # LED pin\nG.setup(17, G.IN)    # button pin\nG.output(18, G.HIGH)\nif G.input(17):\n    print(\"Button pressed\")\nG.cleanup()",
	btn: "# Button operations\nimport RPi.GPIO as G\nG.setmode(G.BCM)\nG.setup(17, G.IN, pull_up_down=G.PUD_UP)\n\ndef on_press(channel):\n    print(\"Button pressed on channel\", channel)\n\nG.add_event_detect(17, G.FALLING, callback=on_press, bouncetime=200)",
	key: "# Keyboard shortcuts\nimport keyboard\ndef on_shortcut():\n    print(\"Saved!\")\nkeyboard.add_hotkey(\"ctrl+s\", on_shortcut)\nkeyboard.wait()   # keep listening",
	web: "# HTTP & web basics\nimport requests\nr = requests.get(\"https://api.example.com/items\")\nprint(\"Status:\", r.status_code)\nif r.ok:\n    for item in r.json():\n        print(item)",
	alg: "# Algorithms & recursion\ndef factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\ndef binary_search(data, target):\n    lo, hi = 0, len(data) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if data[mid] == target:\n            return mid\n        if data[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\nprint(factorial(5), binary_search([1,3,5,7,9], 7))",
	test: "# Testing & debugging\nimport unittest\n\ndef add(a, b):\n    return a + b\n\nclass TestMath(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(add(2, 3), 5)\n\nif __name__ == \"__main__\":\n    unittest.main()"
};

window.BOOKDATA.snips.javascript = {
	hello: "// Hello World\nconsole.log(\"Hello, World!\");",
	vars: "// Variables & constants\nlet name = \"Ali\";\nconst AGE = 25;\nvar old = 1000; // legacy",
	types: "const n = 10;         // number\nconst s = \"text\";     // string\nconst b = true;       // boolean\nconst arr = [1, 2];   // array\nconst obj = {k: \"v\"}; // object\nconsole.log(typeof n, typeof s, typeof b);",
	ops: "let a = 10, b = 3;\nconsole.log(a + b);   // 13\nconsole.log(a % b);   // 1\nconsole.log(a === b); // strict equality\nconsole.log(a > b);   // true",
	strs: "const s = \"Hello AlioStore\";\nconsole.log(s.toUpperCase());\nconsole.log(s.toLowerCase());\nconsole.log(s.replace(\"Hello\", \"Hi\"));\nconsole.log(s.split(\" \").join(\" | \"));\nconsole.log(\"Length: \" + s.length);",
	nums: "const x = \"42\";\nconst n = parseInt(x, 10);\nconst f = parseFloat(\"3.5\");\nconst back = String(100);\nconsole.log(n + 1, f, back);",
	if: "const age = 18;\nif (age >= 18) { console.log(\"Adult\"); }\nelse if (age >= 13) { console.log(\"Teen\"); }\nelse { console.log(\"Child\"); }",
	loop: "for (let i = 0; i < 5; i++) { console.log(i); }\nlet n = 0;\nwhile (n < 3) { console.log(\"tick\", n); n++; }\nconst arr = [1, 2, 3];\nfor (const v of arr) { console.log(v); }",
	switch: "function desc(code) {\n  switch (code) {\n    case 200: return \"OK\";\n    case 404: return \"Not Found\";\n    default: return \"Unknown\";\n  }\n}\nconsole.log(desc(404));",
	func: "function greet(name, greeting = \"Hello\") {\n  return greeting + \", \" + name + \"!\";\n}\nconst greetArrow = (n) => \"Hi, \" + n + \"!\";\nconsole.log(greet(\"Ali\"));\nconsole.log(greetArrow(\"Ali\"));",
	class: "class Book {\n  constructor(title, pages) {\n    this.title = title;\n    this.pages = pages;\n  }\n  info() {\n    return this.title + \" (\" + this.pages + \" pages)\";\n  }\n}\nconst b = new Book(\"AlioStore Notes\", 80);\nconsole.log(b.info());",
	arr: "const fruits = [\"apple\", \"banana\", \"cherry\"];\nfruits.push(\"date\");\nfruits.splice(fruits.indexOf(\"banana\"), 1);\nconsole.log(fruits);\nconsole.log(fruits[0]);\nfruits.forEach((f) => console.log(f));",
	map: "const user = { name: \"Ali\", age: 25 };\nconsole.log(user[\"name\"]);\nuser[\"email\"] = \"ali@example.com\";\nfor (const k in user) { console.log(k, \"=\", user[k]); }",
	file: "// Reading & writing files (Node.js)\nconst fs = require(\"fs\");\nfs.writeFileSync(\"note.txt\", \"Hello file!\\n\");\nconst text = fs.readFileSync(\"note.txt\", \"utf8\");\nconsole.log(text);",
	json: "const data = { name: \"Ali\", languages: [\"JavaScript\", \"Python\"] };\nconst text = JSON.stringify(data);\nconst loaded = JSON.parse(text);\nconsole.log(loaded.name, loaded.languages[0]);",
	input: "const readline = require(\"readline\");\nconst rl = readline.createInterface({ input: process.stdin, output: process.stdout });\nrl.question(\"What is your name? \", (name) => {\n  console.log(\"Hello\", name);\n  rl.close();\n});",
	env: "const port = process.env.PORT || 8080;\nconsole.log(\"Port:\", port);\nconsole.log(\"HOME:\", process.env.HOME);",
	time: "const now = new Date();\nconsole.log(now.toISOString());\nconsole.log(now.toLocaleString());",
	try: "try {\n  JSON.parse(\"not-json\");\n} catch (e) {\n  console.log(\"Error:\", e.message);\n} finally {\n  console.log(\"Done\");\n}",
	hash: "const crypto = require(\"crypto\");\nfunction hashPassword(pw) {\n  return crypto.createHash(\"sha256\").update(pw).digest(\"hex\");\n}\nconsole.log(hashPassword(\"secret123\"));",
	sys: "console.log(\"argv:\", process.argv);\nconsole.log(\"platform:\", process.platform);\nconsole.log(\"arch:\", process.arch);\nconsole.log(\"cwd:\", process.cwd());\nconsole.log(\"memory:\", process.memoryUsage().rss);",
	gpio: "// Board configurations (GPIO) via onoff (Linux/Node)\nconst Gpio = require(\"onoff\").Gpio;\nconst led = new Gpio(18, \"out\");\nconst button = new Gpio(17, \"in\", \"rising\");\nled.writeSync(1);\nbutton.watch((err, value) => {\n  if (!err) console.log(\"Button pressed\");\n});",
	btn: "const btn = document.getElementById(\"btn\");\nconst lamp = document.getElementById(\"lamp\");\nbtn.addEventListener(\"click\", () => {\n  lamp.classList.toggle(\"on\");\n  console.log(\"Pressed\");\n});",
	key: "document.addEventListener(\"keydown\", (e) => {\n  if (e.ctrlKey && e.key === \"s\") {\n    e.preventDefault();\n    console.log(\"Saved!\");\n  }\n  if (e.key === \"Escape\") console.log(\"Cancelled\");\n});",
	web: "fetch(\"https://api.example.com/items\")\n  .then((r) => r.json())\n  .then((items) => items.forEach((i) => console.log(i)))\n  .catch((err) => console.log(\"Error:\", err.message));",
	alg: "function factorial(n) {\n  return n <= 1 ? 1 : n * factorial(n - 1);\n}\nfunction binarySearch(data, target) {\n  let lo = 0, hi = data.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (data[mid] === target) return mid;\n    if (data[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}\nconsole.log(factorial(5), binarySearch([1, 3, 5, 7, 9], 7));",
	test: "function add(a, b) { return a + b; }\n\nfunction testAdd() {\n  const cases = [[2, 3, 5], [-1, 1, 0], [0, 0, 0]];\n  for (const [a, b, expected] of cases) {\n    if (add(a, b) !== expected) {\n      throw new Error(\"FAIL \" + a + \"+\" + b + \"=\" + add(a, b));\n    }\n  }\n  console.log(\"All tests passed\");\n}\ntestAdd();"
};