window.BOOKDATA = {

	books: [
		{ id: "python", title: "Python", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The Python Programming Notes & Reference" },
		{ id: "javascript", title: "JavaScript", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The JavaScript Programming Notes & Reference" },
		{ id: "java", title: "Java", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The Java Programming Notes & Reference" },
		{ id: "cpp", title: "C++", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The C++ Programming Notes & Reference" },
		{ id: "go", title: "Go", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The Go Programming Notes & Reference" },
		{ id: "rust", title: "Rust", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The Rust Programming Notes & Reference" },
		{ id: "php", title: "PHP", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The PHP Programming Notes & Reference" },
		{ id: "swift", title: "Swift", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The Swift Programming Notes & Reference" },
		{ id: "kotlin", title: "Kotlin", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The Kotlin Programming Notes & Reference" },
		{ id: "ruby", title: "Ruby", author: "Alio Kamara & Tessie", editor: "Alio Kamara & Tessie", writer: "Alio Kamara & Tessie", intro: "The Ruby Programming Notes & Reference" }
	],

	modules: [
		{ m: "Module 1 - Foundations", t: [
			["1_1", "Introduction & History", "hello"],
			["1_2", "Why Use {L}", "hello"],
			["1_3", "Installation & Setup", "hello"],
			["1_4", "Hello World", "hello"],
			["1_5", "IDE & Tooling", "hello"],
			["1_6", "Run, Build & Debug", "hello"],
			["1_7", "Comments & Documentation", "hello"],
			["1_8", "Project Layout", "file"]
		] },
		{ m: "Module 2 - Core Syntax", t: [
			["2_1", "Variables & Constants", "vars"],
			["2_2", "Data Types", "types"],
			["2_3", "Operators", "ops"],
			["2_4", "Strings & Text", "strs"],
			["2_5", "Numbers & Conversion", "nums"],
			["2_6", "Conditionals (if/else)", "if"],
			["2_7", "Loops (for/while)", "loop"],
			["2_8", "Switch & Case", "switch"]
		] },
		{ m: "Module 3 - Functions & OOP", t: [
			["3_1", "Functions", "func"],
			["3_2", "Parameters & Return Values", "func"],
			["3_3", "Scope & Lifetime", "func"],
			["3_4", "Classes & Objects", "class"],
			["3_5", "Inheritance & Polymorphism", "class"],
			["3_6", "Interfaces & Abstract Types", "class"],
			["3_7", "Arrays & Collections", "arr"],
			["3_8", "Dictionaries & Maps", "map"]
		] },
		{ m: "Module 4 - Data & I/O", t: [
			["4_1", "Reading Files", "file"],
			["4_2", "Writing Files", "file"],
			["4_3", "JSON & Data Formats", "json"],
			["4_4", "Working with Databases", "file"],
			["4_5", "Reading User Input", "input"],
			["4_6", "Output & Logging", "hello"],
			["4_7", "Environment & Configuration", "env"],
			["4_8", "Date & Time", "time"]
		] },
		{ m: "Module 5 - Errors & Security", t: [
			["5_1", "Exceptions & Errors", "try"],
			["5_2", "Try / Catch Handling", "try"],
			["5_3", "Error Logging", "try"],
			["5_4", "Security Functions", "hash"],
			["5_5", "Hashing & Encryption", "hash"],
			["5_6", "Input Validation", "hash"],
			["5_7", "Authentication Basics", "hash"],
			["5_8", "Secure Coding Tips", "hash"]
		] },
		{ m: "Module 6 - System & Hardware", t: [
			["6_1", "System Programming", "sys"],
			["6_2", "Processes & Threads", "sys"],
			["6_3", "Memory Management", "sys"],
			["6_4", "Board Configurations (GPIO)", "gpio"],
			["6_5", "Interrupts & Timers", "gpio"],
			["6_6", "Serial Ports & Connectivity", "gpio"],
			["6_7", "Device I/O", "gpio"],
			["6_8", "CPU & OS Information", "sys"]
		] },
		{ m: "Module 7 - UI & Buttons", t: [
			["7_1", "Button Operations", "btn"],
			["7_2", "Button Debouncing", "btn"],
			["7_3", "Mouse & Click Events", "btn"],
			["7_4", "Toggle States & Switches", "btn"],
			["7_5", "Sliders & Ranges", "btn"],
			["7_6", "Focus & Forms", "btn"],
			["7_7", "Touch & Gestures", "btn"],
			["7_8", "UI Layout Hints", "btn"]
		] },
		{ m: "Module 8 - Keyboard & Shortcuts", t: [
			["8_1", "Keyboard Shortcuts", "key"],
			["8_2", "Key Events", "key"],
			["8_3", "Hotkey Combinations", "key"],
			["8_4", "Key Codes", "key"],
			["8_5", "Modifiers (Ctrl/Shift/Alt)", "key"],
			["8_6", "Shortcut Tables", "key"],
			["8_7", "Accessibility Keys", "key"],
			["8_8", "Terminal Shortcuts", "key"]
		] },
		{ m: "Module 9 - Web & Networking", t: [
			["9_1", "HTTP Basics", "web"],
			["9_2", "HTTP Requests / Fetch", "web"],
			["9_3", "Website Building Phrases", "web"],
			["9_4", "HTML & CSS Integration", "web"],
			["9_5", "REST API Design", "web"],
			["9_6", "Sessions & Cookies", "web"],
			["9_7", "WebSockets", "web"],
			["9_8", "Deploying to the Web", "web"]
		] },
		{ m: "Module 10 - Practice & Interview", t: [
			["10_1", "Algorithms Basics", "alg"],
			["10_2", "Recursion", "alg"],
			["10_3", "Searching", "alg"],
			["10_4", "Sorting", "alg"],
			["10_5", "Testing", "test"],
			["10_6", "Debugging", "test"],
			["10_7", "Best Practices", "test"],
			["10_8", "Interview Questions", "test"]
		] }
	],

	notes: {
		"1_1": "<p><b>{L}</b> was designed to solve real-world programming problems. Its history shapes how we write code today. This chapter explains the origins, design goals, and where it is used in industry.</p>",
		"1_2": "<p>Why choose {L}? It is chosen for readability, performance, ecosystem, or safety. Understanding the strengths of the language helps you pick the right tool for a task, from web services to hardware.</p>",
		"1_3": "<p>Installing {L} is the first step. You install the official toolchain or interpreter, verify the version in the terminal, and prepare your machine for writing programs. Modern installers also set up the package manager.</p>",
		"1_4": "<p>The classic first program prints a greeting to the screen. It verifies that your setup works and shows the basic structure of the language: entry point, statements, and output.</p>",
		"1_5": "<p>An IDE or code editor (VS Code, IntelliJ, Vim) makes {L} development productive with syntax highlighting, autocomplete, and integrated debuggers. This chapter surveys the common tooling choices.</p>",
		"1_6": "<p>Compiling or running a program turns source code into action. Debuggers let you pause execution, inspect variables, and step through code line by line to find bugs.</p>",
		"1_7": "<p>Comments explain code to humans and are ignored by the machine. Documenting functions and tricky logic keeps a codebase maintainable and makes it readable for other developers.</p>",
		"1_8": "<p>A clean project layout separates source files, dependencies, and configuration. Following a standard directory structure makes a {L} project easy to navigate, test, and build.</p>",
		"2_1": "<p>Variables store values that your program can change; constants hold values that never change. Meaningful names and correct initialization prevent many early bugs.</p>",
		"2_2": "<p>Every value in {L} has a data type: numbers, text, booleans, and structured containers. The type system decides which operations are valid and how values behave in memory.</p>",
		"2_3": "<p>Operators combine values: arithmetic (+, -, *, /), comparison (==, !=, &lt;), and logical (and, or, not). Precedence rules decide the order in which operations run.</p>",
		"2_4": "<p>Strings are sequences of characters used for text. Common operations include comparing, joining, slicing, changing case, and searching for substrings.</p>",
		"2_5": "<p>Numbers come in integer and fractional forms. Conversion between types (casting) must be handled carefully to avoid losing data or precision.</p>",
		"2_6": "<p>Conditionals let your program make decisions with if and else branches. Conditions evaluate to true or false, and only the matching branch runs.</p>",
		"2_7": "<p>Loops repeat a block of code. for-loops iterate a known number of times or over a collection; while-loops repeat until a condition becomes false.</p>",
		"2_8": "<p>A switch statement selects one of many branches based on a value. It is often clearer than long chains of if/else when comparing a single value.</p>",
		"3_1": "<p>Functions bundle reusable logic under a name. They accept inputs (parameters), run a sequence of statements, and return results. Good functions do one job well.</p>",
		"3_2": "<p>Parameters are the inputs a function receives; return values are its outputs. Defaults and handling optional inputs make functions flexible and safe.</p>",
		"3_3": "<p>Scope controls where a variable is visible: inside a block, inside a function, or across the whole program. Understanding scope prevents collisions and accidental changes.</p>",
		"3_4": "<p>Classes bundle data (fields) and behavior (methods) into objects. Object-oriented modeling mirrors real-world entities such as Book, User, or Order.</p>",
		"3_5": "<p>Inheritance lets a class reuse and extend another class behavior. Polymorphism allows one interface to drive many implementations.</p>",
		"3_6": "<p>Interfaces and abstract types define a contract without forcing a concrete implementation. Components built against an interface are easier to test and swap.</p>",
		"3_7": "<p>Arrays and collections hold many values of the same type. They support indexing, adding, removing, and iterating over items.</p>",
		"3_8": "<p>Dictionaries / maps / objects store key-value pairs. Lookup by key is fast, which makes them ideal for records, configs, and caches.</p>",
		"4_1": "<p>Reading files loads text or data from disk into your program. You open a path, read its contents (or line by line), and close the resource cleanly.</p>",
		"4_2": "<p>Writing files persists program output to disk. You create or overwrite a file, write content, and flush or close it so the data is saved safely.</p>",
		"4_3": "<p>JSON is the universal data interchange format. Serialization converts objects to JSON text; deserialization parses JSON back into program objects.</p>",
		"4_4": "<p>Databases store structured data persistently. You connect, run queries with parameters, and manage records safely through transactions and prepared statements.</p>",
		"4_5": "<p>Reading user input lets programs become interactive. Input arrives from the keyboard and must usually be validated and converted before use.</p>",
		"4_6": "<p>Output and logging show results and diagnostic messages. Well-placed logging makes production systems debuggable without stopping them.</p>",
		"4_7": "<p>Environment configuration separates settings (credentials, ports, flags) from code. Reading from environment variables keeps secrets out of source control.</p>",
		"4_8": "<p>Date and time handling covers timestamps, formatting, and time zones. Libraries and built-ins help avoid classic off-by-one errors.</p>",
		"5_1": "<p>Errors and exceptions signal that something went wrong at runtime. Knowing the difference between syntax, runtime, and logic errors helps you diagnose failures.</p>",
		"5_2": "<p>Try / catch blocks attempt risky code and handle failures gracefully instead of crashing. Always recover or re-throw with context.</p>",
		"5_3": "<p>Error logging records the details of failures - time, message, stack trace - so you can trace what happened. Structured logs are searchable and alertable.</p>",
		"5_4": "<p>Security functions protect data: hashing, encryption, and token generation. Use well-audited libraries and never write your own cryptography.</p>",
		"5_5": "<p>Hashing produces a fixed-size fingerprint of data; encryption hides data reversibly with a key. Salting passwords and using modern algorithms is essential.</p>",
		"5_6": "<p>Input validation rejects bad data before it is processed. Validate length, type, format, and allowed values to prevent injection and crashes.</p>",
		"5_7": "<p>Authentication confirms who a user is. Concepts include passwords, tokens, sessions, hashing credentials, and rate-limiting attempts.</p>",
		"5_8": "<p>Secure coding means avoiding injection, not exposing secrets, and never trusting untrusted input. Review checklists catch the most common flaws.</p>",
		"6_1": "<p>System programming talks to the operating system: processes, files, memory, and hardware. It gives programs power and responsibility over machine resources.</p>",
		"6_2": "<p>Processes are independent running programs; threads are lighter execution units inside one process. Concurrency enables multitasking but needs careful synchronization.</p>",
		"6_3": "<p>Memory management allocates and frees memory. Manual languages require ownership discipline; managed languages use garbage collection or compile-time safety.</p>",
		"6_4": "<p>Board configurations control hardware pins (GPIO). You set pin modes (input/output), write signals to drive LEDs, or read switches on microcontrollers and single-board computers.</p>",
		"6_5": "<p>Interrupts notify code that an event occurred; timers schedule actions. They are essential for responsive embedded and real-time applications.</p>",
		"6_6": "<p>Serial ports and buses (UART, I2C, SPI) connect devices and peripherals. Data travels byte by byte over well-defined protocols.</p>",
		"6_7": "<p>Device I/O reads sensors and drives actuators. Reading a value, conditioning the signal, and reacting are the core of embedded programming.</p>",
		"6_8": "<p>Querying CPU and OS information (cores, platform, environment) lets software adapt to its host at runtime.</p>",
		"7_1": "<p>Button operations handle presses: press, release, click. A handler reacts to the event and updates state or triggers an action.</p>",
		"7_2": "<p>Mechanical buttons bounce electrically. Debouncing ignores rapid false transitions by reading after a short settle delay or using a state machine.</p>",
		"7_3": "<p>Mouse and click events track pointer position and button presses. Click, hover, and drag events drive interactive interfaces.</p>",
		"7_4": "<p>Toggles and switches flip between two states (on/off). A flag plus a listener keeps the UI and the state in sync.</p>",
		"7_5": "<p>Sliders and range inputs let users pick a value from a continuous range. The current value is read live or on release.</p>",
		"7_6": "<p>Focus and forms manage text fields, validation, and submission order. Focus events help UIs show helpful feedback.</p>",
		"7_7": "<p>Touch and gestures handle taps, swipes, and pinch on touch screens. Bridging taps and pointer events supports hybrid devices.</p>",
		"7_8": "<p>UI layout hints - grids, spacing, and responsive rules - keep interfaces usable across screen sizes.</p>",
		"8_1": "<p>Keyboard shortcuts trigger actions with key presses. Fast paths for common tasks drastically improve productivity.</p>",
		"8_2": "<p>Key events fire when a key is pressed or released. Handlers inspect which key was pressed and whether it repeats.</p>",
		"8_3": "<p>Hotkey combinations bind a modifier-plus-key sequence (Ctrl+S) to an action. Order and key values must be matched precisely.</p>",
		"8_4": "<p>Key codes identify physical keys independently of the characters typed. They matter for layout-independent shortcuts and games.</p>",
		"8_5": "<p>Modifiers - Ctrl, Shift, Alt, Meta - combine with other keys. Reading modifier state enables chord shortcuts.</p>",
		"8_6": "<p>Shortcut tables document every binding so users can discover them. Consistency across apps reduces the learning cost.</p>",
		"8_7": "<p>Accessibility keys include Tab navigation, Enter activation, and Escape. Keyboard-complete UIs are fully usable without a mouse.</p>",
		"8_8": "<p>Terminal shortcuts (Ctrl+C, Ctrl+Z, arrows, history) make command-line work fast. They are the daily toolkit of every developer.</p>",
		"9_1": "<p>HTTP is the protocol of the web: requests and responses with methods, headers, and status codes. Understanding it underpins all client-server work.</p>",
		"9_2": "<p>Making HTTP requests fetches resources or sends data to servers. Clients set headers, parse JSON responses, and handle errors.</p>",
		"9_3": "<p>Website building phrases are the vocabulary of the web: web page, endpoint, API, hosting, domain, SEO, responsive design, and more. Shared terms keep teams aligned.</p>",
		"9_4": "<p>HTML and CSS integration strengthen a page: HTML gives structure, CSS styles it, and {L} adds behavior and data.</p>",
		"9_5": "<p>REST API design uses nouns as resources and HTTP methods (GET, POST, PUT, DELETE) as actions. Predictable URLs and status codes scale well.</p>",
		"9_6": "<p>Sessions and cookies keep state between requests so servers remember who you are and what you have done.</p>",
		"9_7": "<p>WebSockets open a persistent two-way channel for chat, games, and live dashboards - unlike the HTTP request/response cycle.</p>",
		"9_8": "<p>Deployment ships your app to a server or platform: build, configure, run, and monitor. CI/CD automates the pipeline.</p>",
		"10_1": "<p>Algorithms are step-by-step procedures to solve problems. Understanding complexity (big O) tells you how a solution scales.</p>",
		"10_2": "<p>Recursion solves a problem by calling itself on a smaller piece. Every recursive function needs a base case that stops the calls.</p>",
		"10_3": "<p>Searching finds items in data. Linear search checks each item; binary search halves the range on sorted data.</p>",
		"10_4": "<p>Sorting orders collections. Bubble, selection, and quicksort differ in speed, simplicity, and stability.</p>",
		"10_5": "<p>Testing verifies behavior automatically. Unit tests feed inputs and check expected outputs; they rerun quickly as code changes.</p>",
		"10_6": "<p>Debugging finds and fixes defects: reproduce, isolate, inspect state, and verify the fix. Print statements and breakpoints are the tools.</p>",
		"10_7": "<p>Best practices - readability, naming, error handling, and reviews - keep software maintainable and reduce defects over time.</p>",
		"10_8": "<p>Interview questions test fundamentals: data structures, algorithms, and design. Practice handwriting code and explaining trade-offs.</p>"
	}

};