window.BOOKDATA || (window.BOOKDATA = {});

window.BOOKDATA.snips.ruby = {
	hello: "# Hello World\nputs \"Hello, World!\"",
	vars: "name = \"Ali\"\nage = 25\nMAX_USERS = 100\ntotal = 50",
	types: "i = 10           # Integer\nf = 3.14         # Float\ns = \"hello\"      # String\nb = true         # Boolean\narr = [1,2,3]    # Array\nh = {k: \"v\"}     # Hash",
	ops: "a, b = 10, 3\nputs a + b   # 13\nputs a % b   # 1\nputs a > b   # true",
	strs: "s = \"Hello AlioStore\"\nputs s.upcase\nputs s.downcase\nputs s.gsub(\"Hello\", \"Hi\")\nputs s.split(\" \").join(\"-\")",
	nums: "x = \"42\"\nn = x.to_i\nf = \"3.5\".to_f\ns = 100.to_s\nputs n + 1, f, s",
	if: "age = 18\nif age >= 18\n  puts \"Adult\"\nelsif age >= 13\n  puts \"Teen\"\nelse\n  puts \"Child\"\nend",
	loop: "5.times { |i| puts i }\nn = 0\nwhile n < 3\n  puts \"tick #{n}\"\n  n += 1\nend\n[1,2,3].each { |v| puts v }",
	switch: "def desc(code)\n  case code\n  when 200 then \"OK\"\n  when 404 then \"Not Found\"\n  else \"Unknown\"\n  end\nend\nputs desc(404)",
	func: "def greet(name, greeting = \"Hello\")\n  \"#{greeting}, #{name}!\"\nend\nputs greet(\"Ali\")",
	class: "class Book\n  attr_accessor :title, :pages\n  def initialize(title, pages)\n    @title = title\n    @pages = pages\n  end\n  def info\n    \"#{@title} (#{@pages} pages)\"\n  end\nend\nb = Book.new(\"AlioStore Notes\", 80)\nputs b.info",
	arr: "fruits = %w[apple banana cherry]\nfruits << \"date\"\nfruits.delete(\"banana\")\np fruits\nfruits.each { |f| puts f }",
	map: "user = { name: \"Ali\", age: 25 }\nputs user[:name]\nuser[:email] = \"ali@example.com\"\nuser.each { |k, v| puts \"#{k}=#{v}\" }",
	file: "File.write(\"note.txt\", \"Hello file!\\n\")\ntext = File.read(\"note.txt\")\nputs text",
	json: "require \"json\"\ndata = { \"name\" => \"Ali\", \"languages\" => [\"Ruby\", \"JS\"] }\ntext = data.to_json\nloaded = JSON.parse(text)\nputs loaded[\"name\"]",
	input: "print \"What is your name? \"\nname = gets.chomp\nputs \"Hello #{name}\"",
	env: "port = ENV.fetch(\"PORT\", \"8080\")\nputs \"Port: #{port}\"\nputs \"HOME: #{ENV[\"HOME\"]}\"",
	time: "now = Time.now\nputs now\nputs now.strftime(\"%Y-%m-%d %H:%M:%S\")",
	try: "begin\n  Integer(\"not-a-number\")\nrescue ArgumentError => e\n  puts \"Error: #{e.message}\"\nensure\n  puts \"Done\"\nend",
	hash: "require \"digest\"\nputs Digest::SHA256.hexdigest(\"secret123\")",
	sys: "p RUBY_PLATFORM\np RUBY_VERSION\np Process.pid\np ENV[\"OS\"]",
	gpio: "# Board configurations (GPIO) via rpi_gpio\nled = 18\nbtn = 17\n# setup pins, then:\ndigital_write(led, HIGH)\nif digital_read(btn) == HIGH\n  puts \"Button pressed\"\nend",
	btn: "last = HIGH\nloop do\n  current = digital_read(17)\n  puts \"Pressed\" if current == LOW && last == HIGH\n  last = current\n  sleep 0.05\nend",
	key: "# Read a single key from terminal\nsystem(\"stty raw -echo\")\nch = STDIN.getc\nsystem(\"stty -raw echo\")\nputs \"Key: #{ch.inspect}\"",
	web: "require \"net/http\"\nrequire \"json\"\nresp = Net::HTTP.get_response(URI(\"https://api.example.com/items\"))\nputs resp.code\nputs resp.body",
	alg: "def factorial(n)\n  n <= 1 ? 1 : n * factorial(n - 1)\nend\ndef binary_search(data, target)\n  lo, hi = 0, data.length - 1\n  while lo <= hi\n    mid = (lo + hi) / 2\n    return mid if data[mid] == target\n    lo = mid + 1 if data[mid] < target\n    hi = mid - 1 if data[mid] > target\n  end\n  -1\nend\nputs factorial(5)\nputs binary_search([1,3,5,7,9], 7)",
	test: "require \"minitest/autorun\"\n\ndef add(a, b)\n  a + b\nend\n\nclass MathTest < Minitest::Test\n  def test_add\n    assert_equal 5, add(2, 3)\n  end\nend"
};

window.BOOKDATA.snips.swift = {
	hello: "// Hello World\nprint(\"Hello, World!\")",
	vars: "var name = \"Ali\"\nlet age = 25\nlet maxUsers = 100",
	types: "let i = 10        // Int\nlet f = 3.14      // Double\nlet s = \"hello\"   // String\nlet b = true      // Bool\nlet arr = [1, 2, 3]\nlet dict = [\"k\": \"v\"]",
	ops: "let a = 10\nlet b = 3\nprint(a + b)   // 13\nprint(a % b)   // 1\nprint(a > b)   // true",
	strs: "var s = \"Hello AlioStore\"\nprint(s.uppercased())\nprint(s.lowercased())\nprint(s.replacingOccurrences(of: \"Hello\", with: \"Hi\"))\nfor part in s.split(separator: \" \") { print(part) }",
	nums: "let x = \"42\"\nlet n = Int(x) ?? 0\nlet f = Double(\"3.5\") ?? 0\nlet back = String(100)\nprint(n, f, back)",
	if: "let age = 18\nif age >= 18 {\n    print(\"Adult\")\n} else if age >= 13 {\n    print(\"Teen\")\n} else {\n    print(\"Child\")\n}",
	loop: "for i in 0..<5 { print(i) }\nvar n = 0\nwhile n < 3 { print(\"tick\", n); n += 1 }",
	switch: "func desc(_ code: Int) -> String {\n    switch code {\n    case 200: return \"OK\"\n    case 404: return \"Not Found\"\n    default: return \"Unknown\"\n    }\n}\nprint(desc(404))",
	func: "func greet(_ name: String, greeting: String = \"Hello\") -> String {\n    return \"\\(greeting), \\(name)!\"\n}\nprint(greet(\"Ali\"))",
	class: "class Book {\n    var title: String\n    var pages: Int\n    init(_ title: String, _ pages: Int) {\n        self.title = title\n        self.pages = pages\n    }\n    func info() -> String {\n        return \"\\(title) (\\(pages) pages)\"\n    }\n}\nlet b = Book(\"AlioStore Notes\", 80)\nprint(b.info())",
	arr: "var fruits = [\"apple\", \"banana\", \"cherry\"]\nfruits.append(\"date\")\nfruits.remove(at: fruits.firstIndex(of: \"banana\")!)\nprint(fruits)\nfor f in fruits { print(f) }",
	map: "var user = [\"name\": \"Ali\", \"age\": \"25\"]\nprint(user[\"name\"] ?? \"\")\nuser[\"email\"] = \"ali@example.com\"\nfor (k, v) in user { print(\"\\(k)=\\(v)\") }",
	file: "import Foundation\n// writing\ntry? \"Hello file!\\n\".write(toFile: \"note.txt\", atomically: true, encoding: .utf8)\n// reading\nif let text = try? String(contentsOfFile: \"note.txt\", encoding: .utf8) {\n    print(text)\n}",
	json: "import Foundation\nstruct User: Codable {\n    let name: String\n    let languages: [String]\n}\nlet data = User(name: \"Ali\", languages: [\"Swift\", \"JS\"])\nif let d = try? JSONEncoder().encode(data),\n   let text = String(data: d, encoding: .utf8) {\n    print(text)\n}",
	input: "print(\"What is your name? \", terminator: \"\")\nlet name = readLine() ?? \"\"\nprint(\"Hello \\(name)\")",
	env: "import Foundation\nlet port = ProcessInfo.processInfo.environment[\"PORT\"] ?? \"8080\"\nprint(\"Port: \\(port)\")",
	time: "import Foundation\nlet now = Date()\nlet f = DateFormatter()\nf.dateFormat = \"yyyy-MM-dd HH:mm:ss\"\nprint(f.string(from: now))",
	try: "enum InputError: Error { case notANumber }\nfunc parse(_ s: String) throws -> Int {\n    guard let n = Int(s) else { throw InputError.notANumber }\n    return n\n}\ndo {\n    try print(parse(\"42\"))\n} catch {\n    print(\"Error: \\(error)\")\n}",
	hash: "import Foundation\nimport CryptoKit\nlet data = Data(\"secret123\".utf8)\nlet digest = SHA256.hash(data: data)\nprint(digest.map { String(format: \"%02x\", $0) }.joined())",
	sys: "import Foundation\nlet info = ProcessInfo.processInfo\nprint(info.operatingSystemVersionString)\nprint(\"CPUs:\", info.activeProcessorCount)\nprint(\"Mem:\", info.physicalMemory)",
	gpio: "// Board configurations (GPIO) - Swift on Raspberry Pi\nimport SwiftyGPIO\nlet gpios = SwiftyGPIO.GPIOs(for: .RaspberryPi3)\nvar led = gpios[.P18]!\nled.direction = .OUT\nled.value = 1\nvar btn = gpios[.P17]!\nbtn.direction = .IN\nif btn.value == 1 { print(\"Button pressed\") }",
	btn: "import UIKit\nclass VC: UIViewController {\n    override func viewDidLoad() {\n        let btn = UIButton(type: .system)\n        btn.setTitle(\"Click me\", for: .normal)\n        btn.addTarget(self, action: #selector(tapped), for: .touchUpInside)\n        btn.center = view.center\n        view.addSubview(btn)\n    }\n    @objc func tapped() { print(\"Pressed\") }\n}",
	key: "// macOS / AppKit key handler\noverride func keyDown(with event: NSEvent) {\n    if event.modifierFlags.contains(.command) && event.keyCode == 1 {\n        print(\"Cmd+S\")           // keyCode 1 == s\n    }\n    if event.keyCode == 53 {\n        print(\"Escape\")\n    }\n}",
	web: "import Foundation\nlet url = URL(string: \"https://api.example.com/items\")!\nURLSession.shared.dataTask(with: url) { data, response, error in\n    if let error = error { print(\"Error: \\(error)\"); return }\n    print(String(data: data ?? Data(), encoding: .utf8) ?? \"\")\n}.resume()",
	alg: "func factorial(_ n: Int) -> Int {\n    return n <= 1 ? 1 : n * factorial(n - 1)\n}\nfunc binarySearch(_ data: [Int], _ target: Int) -> Int {\n    var lo = 0, hi = data.count - 1\n    while lo <= hi {\n        let mid = (lo + hi) / 2\n        if data[mid] == target { return mid }\n        if data[mid] < target { lo = mid + 1 } else { hi = mid - 1 }\n    }\n    return -1\n}\nprint(factorial(5), binarySearch([1,3,5,7,9], 7))",
	test: "import XCTest\nfunc add(_ a: Int, _ b: Int) -> Int { return a + b }\nclass MathTest: XCTestCase {\n    func testAdd() {\n        XCTAssertEqual(add(2, 3), 5)\n    }\n}"
};

window.BOOKDATA.snips.kotlin = {
	hello: "// Hello World\nfun main() {\n    println(\"Hello, World!\")\n}",
	vars: "var name = \"Ali\"\nval age = 25      // val = read-only\nconst val MAX_USERS = 100",
	types: "val i: Int = 10\nval f: Double = 3.14\nval s: String = \"hello\"\nval b: Boolean = true\nval arr = listOf(1, 2, 3)\nval map = mapOf(\"k\" to \"v\")",
	ops: "val a = 10\nval b = 3\nprintln(a + b)   // 13\nprintln(a % b)   // 1\nprintln(a > b)   // true",
	strs: "val s = \"Hello AlioStore\"\nprintln(s.uppercase())\nprintln(s.lowercase())\nprintln(s.replace(\"Hello\", \"Hi\"))\nprintln(s.split(\" \").joinToString(\"-\"))",
	nums: "val x = \"42\"\nval n = x.toIntOrNull() ?: 0\nval f = \"3.5\".toDoubleOrNull() ?: 0.0\nval back = 100.toString()\nprintln(\"$n $f $back\")",
	if: "val age = 18\nif (age >= 18) {\n    println(\"Adult\")\n} else if (age >= 13) {\n    println(\"Teen\")\n} else {\n    println(\"Child\")\n}",
	loop: "for (i in 0..4) println(i)\nvar n = 0\nwhile (n < 3) { println(\"tick $n\"); n++ }\nlistOf(1, 2, 3).forEach { println(it) }",
	switch: "fun desc(code: Int) = when (code) {\n    200 -> \"OK\"\n    404 -> \"Not Found\"\n    else -> \"Unknown\"\n}\nprintln(desc(404))",
	func: "fun greet(name: String, greeting: String = \"Hello\") = \"$greeting, $name!\"\nprintln(greet(\"Ali\"))",
	class: "class Book(val title: String, val pages: Int) {\n    fun info() = \"$title ($pages pages)\"\n}\nval b = Book(\"AlioStore Notes\", 80)\nprintln(b.info())",
	arr: "val fruits = mutableListOf(\"apple\", \"banana\", \"cherry\")\nfruits.add(\"date\")\nfruits.remove(\"banana\")\nprintln(fruits)\nfruits.forEach { println(it) }",
	map: "val user = mutableMapOf(\"name\" to \"Ali\", \"age\" to \"25\")\nprintln(user[\"name\"])\nuser[\"email\"] = \"ali@example.com\"\nfor ((k, v) in user) println(\"$k=$v\")",
	file: "import java.io.File\n// writing\nFile(\"note.txt\").writeText(\"Hello file!\\n\")\n// reading\nprintln(File(\"note.txt\").readText())",
	json: "import org.json.JSONObject\nval data = JSONObject().put(\"name\", \"Ali\").put(\"age\", 25)\nval text = data.toString()\nval loaded = JSONObject(text)\nprintln(loaded.getString(\"name\"))",
	input: "println(\"What is your name? \")\nval name = readLine() ?: \"\"\nprintln(\"Hello $name\")",
	env: "val port = System.getenv(\"PORT\") ?: \"8080\"\nprintln(\"Port: $port\")\nprintln(\"OS: ${System.getProperty(\"os.name\")}\")",
	time: "import java.time.LocalDateTime\nimport java.time.format.DateTimeFormatter\nval now = LocalDateTime.now()\nprintln(now.format(DateTimeFormatter.ofPattern(\"yyyy-MM-dd HH:mm:ss\")))",
	try: "try {\n    Integer.parseInt(\"not-a-number\")\n} catch (e: NumberFormatException) {\n    println(\"Error: ${e.message}\")\n} finally {\n    println(\"Done\")\n}",
	hash: "import java.security.MessageDigest\nfun sha256(s: String): String =\n    MessageDigest.getInstance(\"SHA-256\")\n        .digest(s.toByteArray())\n        .joinToString(\"\") { \"%02x\".format(it) }\nprintln(sha256(\"secret123\"))",
	sys: "println(\"cores: ${Runtime.getRuntime().availableProcessors()}\")\nprintln(\"maxMem: ${Runtime.getRuntime().maxMemory()}\")\nprintln(\"OS: ${System.getProperty(\"os.name\")}\")",
	gpio: "// Board configurations (GPIO) - pi4j v2 on Raspberry Pi\nimport com.pi4j.Pi4J\nimport com.pi4j.io.gpio.digital.*\nval pi4j = Pi4J.newAutoContext()\nval led = pi4j.digitalOutput().create(DigitalOutputConfigBuilder()\n    .id(\"led\").address(18).provider(\"pigpio-digital-output\").build())\nled.high()\nval btn = pi4j.digitalInput().create(DigitalInputConfigBuilder()\n    .id(\"btn\").address(17).provider(\"pigpio-digital-input\").build())\nif (btn.isHigh) println(\"Button pressed\")",
	btn: "import android.widget.Button\nclass MainActivity : android.app.Activity() {\n    override fun onCreate(savedInstanceState: android.os.Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n        val btn = findViewById<Button>(R.id.btn)\n        btn.setOnClickListener { println(\"Pressed\") }\n    }\n}",
	key: "// Compose key handler\nimport androidx.compose.ui.input.key.*\nonPreviewKeyEvent = { event ->\n    if (event.isCtrlPressed && event.key == Key.S) {\n        println(\"Saved!\"); true\n    } else false\n}",
	web: "import java.net.URI\nimport java.net.http.HttpClient\nimport java.net.http.HttpRequest\nimport java.net.http.HttpResponse\nval client = HttpClient.newHttpClient()\nval req = HttpRequest.newBuilder(URI(\"https://api.example.com/items\")).GET().build()\nval res = client.send(req, HttpResponse.BodyHandlers.ofString())\nprintln(res.statusCode())\nprintln(res.body())",
	alg: "fun factorial(n: Int): Int = if (n <= 1) 1 else n * factorial(n - 1)\nfun binarySearch(data: List<Int>, target: Int): Int {\n    var lo = 0\n    var hi = data.size - 1\n    while (lo <= hi) {\n        val mid = (lo + hi) / 2\n        when {\n            data[mid] == target -> return mid\n            data[mid] < target -> lo = mid + 1\n            else -> hi = mid - 1\n        }\n    }\n    return -1\n}\nprintln(factorial(5))\nprintln(binarySearch(listOf(1,3,5,7,9), 7))",
	test: "import kotlin.test.*\nfun add(a: Int, b: Int) = a + b\nclass MathTest {\n    @Test\n    fun addWorks() {\n        assertEquals(5, add(2, 3))\n    }\n}"
};