window.BOOKDATA || (window.BOOKDATA = {});

window.BOOKDATA.snips.php = {
	hello: "<?php\necho \"Hello, World!\";\n?>",
	vars: "<?php\n$name = \"Ali\";\n$age = 25;\ndefine(\"MAX_USERS\", 100);\necho $name;\n?>",
	types: "<?php\n$i = 10;           // int\n$f = 3.14;         // float\n$s = \"hello\";      // string\n$b = true;         // bool\n$arr = [1, 2, 3];  // array\n$map = [\"k\" => \"v\"];\n?>",
	ops: "<?php\n$a = 10; $b = 3;\necho ($a + $b) . \"\\n\";  // 13\necho ($a % $b) . \"\\n\";  // 1\nvar_dump($a > $b);      // bool(true)\n?>",
	strs: "<?php\n$s = \"Hello AlioStore\";\necho strtoupper($s) . \"\\n\";\necho strtolower($s) . \"\\n\";\necho str_replace(\"Hello\", \"Hi\", $s) . \"\\n\";\nprint_r(explode(\" \", $s));\n?>",
	nums: "<?php\n$x = \"42\";\n$n = (int)$x;\n$f = (float)\"3.5\";\n$back = (string)100;\necho $n + 1, \" \", $f, \" \", $back;\n?>",
	if: "<?php\n$age = 18;\nif ($age >= 18) {\n    echo \"Adult\";\n} elseif ($age >= 13) {\n    echo \"Teen\";\n} else {\n    echo \"Child\";\n}\n?>",
	loop: "<?php\nfor ($i = 0; $i < 5; $i++) echo \"$i \";\n$n = 0;\nwhile ($n < 3) { echo \"tick $n \"; $n++; }\nforeach ([1,2,3] as $v) echo $v;\n?>",
	switch: "<?php\nfunction desc($code) {\n    switch ($code) {\n        case 200: return \"OK\";\n        case 404: return \"Not Found\";\n        default: return \"Unknown\";\n    }\n}\necho desc(404);\n?>",
	func: "<?php\nfunction greet($name, $greeting = \"Hello\") {\n    return \"$greeting, $name!\";\n}\necho greet(\"Ali\");\n?>",
	class: "<?php\nclass Book {\n    public $title;\n    public $pages;\n    public function __construct($t, $p) {\n        $this->title = $t;\n        $this->pages = $p;\n    }\n    public function info() {\n        return \"{$this->title} ({$this->pages} pages)\";\n    }\n}\n$b = new Book(\"AlioStore Notes\", 80);\necho $b->info();\n?>",
	arr: "<?php\n$fruits = [\"apple\", \"banana\", \"cherry\"];\n$fruits[] = \"date\";\nunset($fruits[array_search(\"banana\", $fruits)]);\nforeach ($fruits as $f) echo $f . \" \";\n?>",
	map: "<?php\n$user = [\"name\" => \"Ali\", \"age\" => 25];\necho $user[\"name\"] . \"\\n\";\n$user[\"email\"] = \"ali@example.com\";\nforeach ($user as $k => $v) echo \"$k=$v\\n\";\n?>",
	file: "<?php\n// writing\nfile_put_contents(\"note.txt\", \"Hello file!\\n\");\n// reading\n$text = file_get_contents(\"note.txt\");\necho $text;\n?>",
	json: "<?php\n$data = [\"name\" => \"Ali\", \"languages\" => [\"PHP\", \"JS\"]];\n$text = json_encode($data);\n$loaded = json_decode($text, true);\necho $loaded[\"name\"] . \" \" . $loaded[\"languages\"][0];\n?>",
	input: "<?php\necho \"What is your name? \";\n$name = trim(fgets(STDIN));\necho \"Hello $name\\n\";\n?>",
	env: "<?php\n$port = getenv(\"PORT\") ?: \"8080\";\necho \"Port: $port\\n\";\necho \"OS: \" . PHP_OS . \"\\n\";\n?>",
	time: "<?php\necho date(\"Y-m-d H:i:s\") . \"\\n\";\necho time() . \"\\n\";\n?>",
	try: "<?php\ntry {\n    if ((int)\"not-a-number\" === 0 && \"not-a-number\" !== \"0\") {\n        throw new Exception(\"Invalid number\");\n    }\n} catch (Exception $e) {\n    echo \"Error: \" . $e->getMessage() . \"\\n\";\n} finally {\n    echo \"Done\\n\";\n}\n?>",
	hash: "<?php\necho password_hash(\"secret123\", PASSWORD_DEFAULT) . \"\\n\";\necho hash(\"sha256\", \"secret123\") . \"\\n\";\n?>",
	sys: "<?php\necho \"OS: \" . PHP_OS . \"\\n\";\necho \"Version: \" . phpversion() . \"\\n\";\necho \"SAPI: \" . PHP_SAPI . \"\\n\";\n?>",
	gpio: "<?php\n// Board configurations (GPIO) - php on Raspberry Pi\n// (real GPIO via a library such as pi-dashboard)\n$led = new Gpio(18, Gpio::OUTPUT);\n$btn = new Gpio(17, Gpio::INPUT);\n$led->write(1);\nif ($btn->read() === 1) {\n    echo \"Button pressed\\n\";\n}\n?>",
	btn: "<?php\n// CLI debounced button loop\n$last = 1;\nwhile (true) {\n    $current = read_gpio(17);\n    if ($current === 0 && $last === 1) echo \"Pressed\\n\";\n    $last = $current;\n    usleep(50000);   // 50 ms debounce\n}\n?>",
	key: "<?php\necho \"Press a key: \";\nsystem(\"stty raw -echo\");\n$ch = fgetc(STDIN);\nsystem(\"stty -raw echo\");\necho \"Key: \" . addcslashes($ch, \"\\n\") . \"\\n\";\n?>",
	web: "<?php\n// HTTP basics with cURL\n$ch = curl_init(\"https://api.example.com/items\");\ncurl_setopt($ch, CURLOPT_RETURNTRANSFER, true);\n$resp = curl_exec($ch);\n$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);\necho $code . \"\\n\" . $resp;\ncurl_close($ch);\n?>",
	alg: "<?php\nfunction factorial($n) {\n    return $n <= 1 ? 1 : $n * factorial($n - 1);\n}\nfunction binarySearch($data, $target) {\n    $lo = 0; $hi = count($data) - 1;\n    while ($lo <= $hi) {\n        $mid = intdiv($lo + $hi, 2);\n        if ($data[$mid] == $target) return $mid;\n        if ($data[$mid] < $target) $lo = $mid + 1;\n        else $hi = $mid - 1;\n    }\n    return -1;\n}\necho factorial(5) . \" \" . binarySearch([1,3,5,7,9], 7);\n?>",
	test: "<?php\nuse PHPUnit\\Framework\\TestCase;\nfunction add($a, $b) { return $a + $b; }\nclass MathTest extends TestCase {\n    public function testAdd() {\n        $this->assertEquals(5, add(2, 3));\n    }\n}\n?>"
};

window.BOOKDATA.snips.go = {
	hello: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"Hello, World!\")\n}",
	vars: "package main\n\nimport \"fmt\"\n\nconst maxUsers = 100\n\nfunc main() {\n\tname := \"Ali\"\n\tage := 25\n\tvar total int = 50\n\tfmt.Println(name, age, total)\n}",
	types: "var i int = 10\nvar f float64 = 3.14\nvar s string = \"hello\"\nvar b bool = true\nvar arr [3]int = [3]int{1, 2, 3}\nvar m map[string]string = map[string]string{\"k\": \"v\"}",
	ops: "a, b := 10, 3\nfmt.Println(a + b)   // 13\nfmt.Println(a % b)   // 1\nfmt.Println(a > b)   // true\nfmt.Println(a == b)  // false",
	strs: "s := \"Hello AlioStore\"\nfmt.Println(strings.ToUpper(s))\nfmt.Println(strings.ToLower(s))\nfmt.Println(strings.ReplaceAll(s, \"Hello\", \"Hi\"))\nfmt.Println(strings.Split(s, \" \"))",
	nums: "x := \"42\"\nn, _ := strconv.Atoi(x)\nf, _ := strconv.ParseFloat(\"3.5\", 64)\nback := strconv.Itoa(100)\nfmt.Println(n+1, f, back)",
	if: "age := 18\nif age >= 18 {\n\tfmt.Println(\"Adult\")\n} else if age >= 13 {\n\tfmt.Println(\"Teen\")\n} else {\n\tfmt.Println(\"Child\")\n}",
	loop: "for i := 0; i < 5; i++ { fmt.Println(i) }\nn := 0\nfor n < 3 { fmt.Println(\"tick\", n); n++ }\nfor _, v := range []int{1, 2, 3} { fmt.Println(v) }",
	switch: "func desc(code int) string {\n\tswitch code {\n\tcase 200:\n\t\treturn \"OK\"\n\tcase 404:\n\t\treturn \"Not Found\"\n\tdefault:\n\t\treturn \"Unknown\"\n\t}\n}\nfmt.Println(desc(404))",
	func: "func greet(name, greeting string) string {\n\treturn greeting + \", \" + name + \"!\"\n}\nfmt.Println(greet(\"Ali\", \"Hello\"))",
	class: "type Book struct {\n\tTitle string\n\tPages int\n}\nfunc (b Book) Info() string {\n\treturn b.Title + \" (\" + strconv.Itoa(b.Pages) + \" pages)\"\n}\nb := Book{\"AlioStore Notes\", 80}\nfmt.Println(b.Info())",
	arr: "fruits := []string{\"apple\", \"banana\", \"cherry\"}\nfruits = append(fruits, \"date\")\nfor _, f := range fruits { fmt.Println(f) }\nfmt.Println(fruits[0])",
	map: "user := map[string]string{\"name\": \"Ali\", \"age\": \"25\"}\nfmt.Println(user[\"name\"])\nuser[\"email\"] = \"ali@example.com\"\nfor k, v := range user { fmt.Println(k, \"=\", v) }",
	file: "// writing\nerr := os.WriteFile(\"note.txt\", []byte(\"Hello file!\\n\"), 0644)\nif err != nil { log.Fatal(err) }\n// reading\ntext, err := os.ReadFile(\"note.txt\")\nif err != nil { log.Fatal(err) }\nfmt.Print(string(text))",
	json: "import \"encoding/json\"\n\ndata := map[string]any{\"name\": \"Ali\", \"languages\": []string{\"Go\", \"JS\"}}\ntext, _ := json.Marshal(data)\nloaded := map[string]any{}\n_ = json.Unmarshal(text, &loaded)\nfmt.Println(loaded[\"name\"])",
	input: "reader := bufio.NewReader(os.Stdin)\nfmt.Print(\"What is your name? \")\nname, _ := reader.ReadString('\\n')\nfmt.Println(\"Hello\", strings.TrimSpace(name))",
	env: "port := os.Getenv(\"PORT\")\nif port == \"\" { port = \"8080\" }\nfmt.Println(\"Port:\", port)\nfmt.Println(\"HOME:\", os.Getenv(\"HOME\"))",
	time: "fmt.Println(time.Now())\nfmt.Println(time.Now().Format(\"2006-01-02 15:04:05\"))",
	try: "func parseInt(s string) (int, error) {\n\tn, err := strconv.Atoi(s)\n\tif err != nil {\n\t\treturn 0, fmt.Errorf(\"invalid number: %v\", err)\n\t}\n\treturn n, nil\n}\nn, err := parseInt(\"42\")\nif err != nil { fmt.Println(\"Error:\", err) }\nfmt.Println(n)",
	hash: "import (\n\t\"crypto/sha256\"\n\t\"encoding/hex\"\n)\n\nsum := sha256.Sum256([]byte(\"secret123\"))\nfmt.Println(hex.EncodeToString(sum[:]))",
	sys: "fmt.Println(\"GOOS:\", runtime.GOOS)\nfmt.Println(\"GOARCH:\", runtime.GOARCH)\nfmt.Println(\"CPUs:\", runtime.NumCPU())\nfmt.Println(\"PID:\", os.Getpid())",
	gpio: "// Board configurations (GPIO) - periph.io on Raspberry Pi\nimport (\n\t\"log\"\n\n\t\"periph.io/x/conn/v3/gpio\"\n\t\"periph.io/x/conn/v3/gpio/gpioreg\"\n\t\"periph.io/x/host/v3\"\n)\n\nfunc main() {\n\thost.Init()\n\tled := gpioreg.ByName(\"GPIO18\")\n\tbtn := gpioreg.ByName(\"GPIO17\")\n\tled.Out(gpio.High)\n\tif btn.Read() == gpio.High {\n\t\tlog.Println(\"Button pressed\")\n\t}\n}",
	btn: "btn := gpioreg.ByName(\"GPIO17\")\nlast := gpio.High\nfor {\n\tcurrent := btn.Read()\n\tif current == gpio.Low && last == gpio.High {\n\t\tfmt.Println(\"Pressed\")\n\t}\n\tlast = current\n\ttime.Sleep(50 * time.Millisecond)   // debounce\n}",
	key: "// read one key from the terminal (golang.org/x/term raw mode)\nfd := int(os.Stdin.Fd())\nold, _ := term.MakeRaw(fd)\ndefer term.Restore(fd, old)\nvar b [1]byte\nos.Stdin.Read(b[:])\nfmt.Printf(\"Key: %q\\n\", b[0])",
	web: "resp, err := http.Get(\"https://api.example.com/items\")\nif err != nil {\n\tfmt.Println(\"Error:\", err)\n\treturn\n}\ndefer resp.Body.Close()\nbody, _ := io.ReadAll(resp.Body)\nfmt.Println(\"Status:\", resp.StatusCode)\nfmt.Println(string(body))",
	alg: "func factorial(n int) int {\n\tif n <= 1 { return 1 }\n\treturn n * factorial(n-1)\n}\nfunc binarySearch(data []int, target int) int {\n\tlo, hi := 0, len(data)-1\n\tfor lo <= hi {\n\t\tmid := (lo + hi) / 2\n\t\tif data[mid] == target { return mid }\n\t\tif data[mid] < target { lo = mid + 1 } else { hi = mid - 1 }\n\t}\n\treturn -1\n}\nfmt.Println(factorial(5), binarySearch([]int{1, 3, 5, 7, 9}, 7))",
	test: "import \"testing\"\n\nfunc add(a, b int) int { return a + b }\n\nfunc TestAdd(t *testing.T) {\n\tif add(2, 3) != 5 {\n\t\tt.Fatal(\"expected 5\")\n\t}\n}"
};

window.BOOKDATA.snips.rust = {
	hello: "fn main() {\n    println!(\"Hello, World!\");\n}",
	vars: "fn main() {\n    let name = \"Ali\";            // immutable by default\n    let mut age = 25;            // mutable\n    const MAX_USERS: i32 = 100;\n    println!(\"{}\", name);\n}",
	types: "let i: i32 = 10;\nlet f: f64 = 3.14;\nlet s: &str = \"hello\";\nlet b: bool = true;\nlet arr: [i32; 3] = [1, 2, 3];\nlet v: Vec<i32> = vec![1, 2, 3];",
	ops: "let a = 10;\nlet b = 3;\nprintln!(\"{}\", a + b);    // 13\nprintln!(\"{}\", a % b);    // 1\nprintln!(\"{}\", a > b);    // true",
	strs: "let s = \"Hello AlioStore\";\nprintln!(\"{}\", s.to_uppercase());\nprintln!(\"{}\", s.to_lowercase());\nprintln!(\"{}\", s.replace(\"Hello\", \"Hi\"));\nfor part in s.split(' ') { println!(\"{}\", part); }",
	nums: "let x = \"42\";\nlet n: i32 = x.parse().unwrap_or(0);\nlet f: f64 = \"3.5\".parse().unwrap_or(0.0);\nlet back = 100.to_string();\nprintln!(\"{} {} {}\", n, f, back);",
	if: "let age = 18;\nif age >= 18 {\n    println!(\"Adult\");\n} else if age >= 13 {\n    println!(\"Teen\");\n} else {\n    println!(\"Child\");\n}",
	loop: "for i in 0..5 { println!(\"{}\", i); }\nlet mut n = 0;\nwhile n < 3 { println!(\"tick {}\", n); n += 1; }\nfor v in [1, 2, 3] { println!(\"{}\", v); }",
	switch: "fn desc(code: i32) -> &'static str {\n    match code {\n        200 => \"OK\",\n        404 => \"Not Found\",\n        _ => \"Unknown\",\n    }\n}\nprintln!(\"{}\", desc(404));",
	func: "fn greet(name: &str, greeting: &str) -> String {\n    format!(\"{}, {}!\", greeting, name)\n}\nfn main() {\n    println!(\"{}\", greet(\"Ali\", \"Hello\"));\n}",
	class: "struct Book {\n    title: String,\n    pages: u32,\n}\nimpl Book {\n    fn new(title: &str, pages: u32) -> Book {\n        Book { title: title.to_string(), pages }\n    }\n    fn info(&self) -> String {\n        format!(\"{} ({} pages)\", self.title, self.pages)\n    }\n}\nlet b = Book::new(\"AlioStore Notes\", 80);\nprintln!(\"{}\", b.info());",
	arr: "let mut fruits = vec![\"apple\", \"banana\", \"cherry\"];\nfruits.push(\"date\");\nfruits.retain(|f| *f != \"banana\");\nprintln!(\"{:?}\", fruits);\nfor f in fruits { println!(\"{}\", f); }",
	map: "use std::collections::HashMap;\nlet mut user = HashMap::new();\nuser.insert(\"name\", \"Ali\");\nuser.insert(\"age\", \"25\");\nprintln!(\"{:?}\", user.get(\"name\"));\nfor (k, v) in &user { println!(\"{}={}\", k, v); }",
	file: "use std::fs;\nfn main() {\n    fs::write(\"note.txt\", \"Hello file!\\n\").expect(\"write failed\");\n    let text = fs::read_to_string(\"note.txt\").expect(\"read failed\");\n    print!(\"{}\", text);\n}",
	json: "use serde_json::{json, Value};\nlet data = json!({\"name\": \"Ali\", \"languages\": [\"Rust\", \"JS\"]});\nlet text = serde_json::to_string(&data).unwrap();\nlet v: Value = serde_json::from_str(&text).unwrap();\nprintln!(\"{}\", v[\"name\"]);",
	input: "use std::io::{self, Write};\nlet mut name = String::new();\nprint!(\"What is your name? \");\nio::stdout().flush().unwrap();\nio::stdin().read_line(&mut name).unwrap();\nprintln!(\"Hello {}\", name.trim());",
	env: "let port = std::env::var(\"PORT\").unwrap_or_else(|_| \"8080\".to_string());\nprintln!(\"Port: {}\", port);\nprintln!(\"HOME: {}\", std::env::var(\"HOME\").unwrap_or_default());",
	time: "use std::time::{SystemTime, UNIX_EPOCH};\nlet now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap();\nprintln!(\"unix seconds: {}\", now.as_secs());",
	try: "fn parse_int(s: &str) -> Result<i32, std::num::ParseIntError> {\n    s.trim().parse()\n}\nmatch parse_int(\"42\") {\n    Ok(n) => println!(\"n = {}\", n),\n    Err(e) => println!(\"Error: {}\", e),\n}",
	hash: "use sha2::{Sha256, Digest};\nlet mut hasher = Sha256::new();\nhasher.update(b\"secret123\");\nlet result = hasher.finalize();\nprintln!(\"{:x}\", result);",
	sys: "println!(\"OS: {}\", std::env::consts::OS);\nprintln!(\"ARCH: {}\", std::env::consts::ARCH);\nprintln!(\"PID: {}\", std::process::id());",
	gpio: "// Board configurations (GPIO) via rppal\nuse rppal::gpio::Gpio;\nlet gpio = Gpio::new().unwrap();\nlet mut led = gpio.get(18).unwrap().into_output();\nlet btn = gpio.get(17).unwrap().into_input();\nled.set_high();\nif btn.is_high() {\n    println!(\"Button pressed\");\n}",
	btn: "use rppal::gpio::Gpio;\nuse std::thread;\nuse std::time::Duration;\nlet btn = Gpio::new().unwrap().get(17).unwrap().into_input();\nlet mut last = btn.is_high();\nloop {\n    let current = btn.is_high();\n    if !current && last { println!(\"Pressed\"); }\n    last = current;\n    thread::sleep(Duration::from_millis(50));   // debounce\n}",
	key: "// raw terminal key read (e.g. with the rustyline crate)\nlet mut rl = rustyline::Editor::<()>::new().unwrap();\nlet line = rl.readline(\"Press a key: \").unwrap();\nprintln!(\"Key: {:?}\", line);",
	web: "use reqwest::blocking::get;\nlet resp = get(\"https://api.example.com/items\").unwrap();\nprintln!(\"Status: {}\", resp.status());\nprintln!(\"{}\", resp.text().unwrap());",
	alg: "fn factorial(n: u32) -> u32 {\n    if n <= 1 { 1 } else { n * factorial(n - 1) }\n}\nfn binary_search(data: &[i32], target: i32) -> Option<usize> {\n    let (mut lo, mut hi) = (0, data.len());\n    while lo < hi {\n        let mid = (lo + hi) / 2;\n        match data[mid].cmp(&target) {\n            std::cmp::Ordering::Equal => return Some(mid),\n            std::cmp::Ordering::Less => lo = mid + 1,\n            std::cmp::Ordering::Greater => hi = mid,\n        }\n    }\n    None\n}\nprintln!(\"{}\", factorial(5));\nprintln!(\"{:?}\", binary_search(&[1, 3, 5, 7, 9], 7));",
	test: "fn add(a: i32, b: i32) -> i32 { a + b }\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n    #[test]\n    fn add_works() {\n        assert_eq!(add(2, 3), 5);\n    }\n}"
};